image: node:10

stages:
  - test
  - deploy
  - build
  - deploy

test:
  stage: test
  services:
    -  name: mongo:latest
       alias: mongodb # should be able to connect at this point
  variables:
    MONGO_URI: 'mongodb://mongodb:27017/koa-mongo-discord'
  before_script:
    - npm install
    # - chmod +x setup_env.sh && ./setup_env.sh
    - echo $MONGO_URI >> .env
    - echo $MONGO_URI
# https://medium.com/@chrishullman/js-testing-mocha-chai-and-istanbul-oh-my-5e68e0cd2e81
  script:
    - npm run test
  coverage:
    '/Statements.*?(\d+(?:\.\d+)?)%/'

build: 
  stage: build
  before_script:
    - npm install
    # - chmod +x setup_env.sh && ./setup_env.sh
    - echo $MONGO_URI >> .env
    - echo $MONGO_URI
# https://medium.com/@chrishullman/js-testing-mocha-chai-and-istanbul-oh-my-5e68e0cd2e81
  script:
    - npm run build
  # Add artifacts here

pages:
  stage: deploy
  before_script:
    - npm install
    - npm install -g typedoc
  script:
    - typedoc --excludeExternals --externalPattern "**/node_modules/**" --ignoreCompilerErrors --name "discord-bot" --mode "file" --out "public/" .
  artifacts:
    paths:
      - public