stages:
  - test
  - build
  - deploy

test:
  image: node:10
  stage: test
  services:
    -  name: mongo:latest
       alias: mongodb # should be able to connect at this point
  variables:
    MONGO_URI: 'mongodb://mongodb:27017/koa-mongo-discord'
  before_script:
    - npm install
    # - chmod +x setup_env.sh && ./setup_env.sh
    - echo $MONGO_URI >> .env
# https://medium.com/@chrishullman/js-testing-mocha-chai-and-istanbul-oh-my-5e68e0cd2e81
  script:
    - npm run test
    - npm run coverage
  coverage:
    '/Statements.*?(\d+(?:\.\d+)?)%/'
  artifacts:
    paths:
      - coverage
    expire_in: 1 week

build-js: 
  image: node:10
  stage: build
  before_script:
    - npm install
    # - chmod +x setup_env.sh && ./setup_env.sh
    - echo $MONGO_URI >> .env
    - echo $MONGO_URI
# https://medium.com/@chrishullman/js-testing-mocha-chai-and-istanbul-oh-my-5e68e0cd2e81
  script:
    - npm run build
  artifacts:
    paths:
      - coverage
      - dist
      - node_modules
    expire_in: 1 day

  # Add artifacts here
# create coverage report
pages:
  image: node:10
  stage: deploy
  dependencies:
    - test
    - build-js
  before_script:
    - npm install
    - npm install -g typedoc
  script:
    - npm run docs
    - mv coverage public || true
  artifacts:
    paths:
      - public

staging:
  dependencies:
    - build-js
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    # Unignore .gitignore file
    - chmod +x setup_env.sh && ./setup_env.sh production
    - sed -i 's/.env/.dev/g' .gitignore
    - mv .env dist || true
    - mv ProcFile dist || true
    - mv package.json || true
    - mv node_modules dist || true
    - cd dist
    - dpl --skip_cleanup --provider=heroku --app=dli-discord-assist --api-key=$HEROKU_API_KEY
  only:
    - master
    # change to tags once it is good