image: node:10

stages:
  - test
  - deploy

test:
  stage: test
  services:
    -  name: mongo:latest
       alias: mongodb # should be able to connect at this point
  variables:
    MONGO_URI: 'mongodb://mongo/koa-mongo-discordt'
  before_script:
    - npm install
    - npm install pm2 -g 
    # - chmod +x setup_env.sh && ./setup_env.sh
    - echo $MONGO_URI >> .env
    - echo $MONGO_URI
# https://medium.com/@chrishullman/js-testing-mocha-chai-and-istanbul-oh-my-5e68e0cd2e81
  script:
    - npm run test
  coverage:
    '/Statements.*?(\d+(?:\.\d+)?)%/'