sudo: true

language: node_js

node_js: 10

services:
  - mongodb

before_script:
  - npm install
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - echo "MONGO_URI=mongodb://localhost:27017/discord-assistant" >> .env
  - echo "DISCORD_TOKEN=not-working" >> .env
script: 
  - npm install -g istanbul typedoc
  - npm run coverage
  - npm install coveralls
  - npm install mocha-lcov-reporter
  - NODE_ENV=testing istanbul cover ./node_modules/ts-mocha/bin/ts-mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - npm run docs
after_success:
  - npm run coveralls || true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: public
  on:
    branch: master