sudo: true

language: node_js

node_js: stable

services:
  - mongodb

before_script:
  - npm install
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - echo "MONGO_URI=mongodb://localhost:27017/discord-assistant" >> .env
  - echo "DISCORD_TOKEN=not-working" >> .env
script: 
  - npm install -g istanbul typedoc
  - npm run coverage
  - istanbul cover ./node_modules/ts-mocha/bin/ts-mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - npm run docs
  - npm run build

after_success:
  - npm run coveralls || true