sudo: true

language: node_js

node_js: stable

services:
  - mongodb

before_script:
  - npm install
script: 
  - npm install -g istanbul
  - npm run coverage
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  - npm run docs
  - npm run build

after_success:
  - npm run coveralls || true